# The class that must be instantiated
_target_: zoo.agents.StableBaselineAgent.StableBaselineAgent

# The agent's hyperparameter tuning configuration
defaults:
  - hp_tuner: stable_baseline_ppo

# The agent's parameters
name: "baseline_${agent.agent_name}"
agent_name: "ppo"
tensorboard_dir: "${tensorboard.directory}"
checkpoint_dir: "${checkpoint.directory}"

# The PPO hyperparameters
learning_rate: 0.0003
n_steps: 2048
batch_size: 64
n_epochs: 10
gamma: 0.95
gae_lambda: 0.95
clip_range: 0.2
clip_range_vf: null
normalize_advantage: True
ent_coef: 0.0
vf_coef: 0.5
max_grad_norm: 0.5
use_sde: False
sde_sample_freq: -1
trainable: True
