# The class that must be instantiated
_target_: zoo.agents.StableBaselineAgent.StableBaselineAgent

# The agent's hyperparameter tuning configuration
defaults:
  - hp_tuner: stable_baseline_a2c

# The agent's parameters
name: "baseline_${agent.agent_name}"
agent_name: "a2c"
tensorboard_dir: "${tensorboard.directory}"
checkpoint_dir: "${checkpoint.directory}"

# The A2C hyperparameters
learning_rate: 0.0007
n_steps: 5
gamma: 0.95
gae_lambda: 1.0
ent_coef: 0.0
vf_coef: 0.5
max_grad_norm: 0.5
rms_prop_eps: 1e-05
use_rms_prop: True
use_sde: False
sde_sample_freq: -1
normalize_advantage: False
trainable: True
