# The class that must be instantiated
_target_: zoo.agents.StableBaselineAgent.StableBaselineAgent

# The agent's hyperparameter tuning configuration
defaults:
  - hp_tuner: stable_baseline_dqn

# The agent's parameters
name: "baseline_${agent.agent_name}"
agent_name: "dqn"
tensorboard_dir: "${tensorboard.directory}"
checkpoint_dir: "${checkpoint.directory}"

# The DQN hyperparameters
learning_rate: 0.0001
buffer_size: 1000000
learning_starts: 50000
batch_size: 32
tau: 1.0
gamma: 0.95
train_freq: 4
gradient_steps: 1
replay_buffer_class: null
replay_buffer_kwargs: null
optimize_memory_usage: False
target_update_interval: 10000
exploration_fraction: 0.1
exploration_initial_eps: 1.0
exploration_final_eps: 0.05
max_grad_norm: 10
trainable: True
