name: "dirichlet_gm_${agent.n_states}"

defaults:
  - action_selection: random

_target_: zoo.agents.DirichletGM.DirichletGM

# Miscellaneous
n_actions: ${environment.n_actions}
n_states: 14
n_observations: 2
discount_factor: 0.95
dataset_size: 500
tensorboard_dir: "${tensorboard.directory}"
checkpoint_dir: "${checkpoint.directory}"
trainable: True
verbose: False
