name: "dirichlet_tgm_${agent.n_states}"

defaults:
  - action_selection: random

_target_: zoo.agents.DirichletTGM.DirichletTGM

# Miscellaneous
n_actions: ${environment.n_actions}
n_states: 6
n_observations: 2
dataset_size: 500
tensorboard_dir: "${tensorboard.directory}"
checkpoint_dir: "${checkpoint.directory}"
trainable: True
verbose: False
