# The class that must be instantiated
_target_: zoo.tasks.DrawEntropyPriorActions.DrawEntropyPriorActions

# The task's parameters
name: "draw_entropy_prior_actions"
seed: 2
max_n_steps: 500000
jump: 500
csv_path: "${oc.env:DATA_DIRECTORY}/${task.task_directory}/entropy_prior_actions/${environment.name}/${agent.name}/${task.seed}/entropy_prior_actions.csv"
figure_path: "${oc.env:DATA_DIRECTORY}/${task.task_directory}/runs/${environment.name}/entropy_prior_actions_${environment.name}_${agent.name}.pdf"
task_directory: "training"
task_data_directory: "${oc.env:DATA_DIRECTORY}/${task.name}/"
